import Link from 'next/link';
import { ArrowRight, Utensils, Activity, User, Sparkles, TrendingUp, ShieldCheck } from 'lucide-react';

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen bg-[#f8fafc] overflow-hidden">

      {/* Decorative Background Blob */}
      <div className="absolute top-0 left-0 w-full h-[800px] overflow-hidden -z-10 bg-slate-50">
        <div className="absolute -top-[20%] -right-[10%] w-[70%] h-[70%] rounded-full bg-emerald-400/10 blur-[120px]" />
        <div className="absolute top-[20%] -left-[10%] w-[50%] h-[50%] rounded-full bg-teal-300/10 blur-[100px]" />
      </div>

      {/* Hero Section */}
      <section className="pt-32 pb-24 md:pt-48 md:pb-32 px-4 relative">
        <div className="container mx-auto max-w-6xl text-center">
          <div className="inline-flex items-center space-x-2 bg-white/60 backdrop-blur-sm border border-slate-200/60 rounded-full px-4 py-1.5 mb-8 shadow-sm">
            <Sparkles className="w-4 h-4 text-emerald-500" />
            <span className="text-sm font-medium text-slate-700">The next generation of diet tracking</span>
          </div>

          <h1 className="text-5xl md:text-7xl font-extrabold text-slate-900 tracking-tight mb-8 leading-[1.1]">
            Your Personal <br className="hidden md:block" />
            <span className="bg-gradient-to-r from-emerald-500 to-teal-500 bg-clip-text text-transparent drop-shadow-sm">AI Dietitian</span>
          </h1>

          <p className="text-lg md:text-xl text-slate-500 max-w-2xl mx-auto mb-12 leading-relaxed">
            Generate highly personalized meal plans, track your calories effortlessly, and achieve your fitness goals with the world's smartest nutrition engine.
          </p>

          <div className="flex flex-col sm:flex-row justify-center items-center gap-4 sm:gap-6">
            <Link
              href="/dashboard/planner"
              className="w-full sm:w-auto px-8 py-4 bg-slate-900 text-white rounded-full font-semibold text-lg hover:bg-emerald-600 transition-all duration-300 shadow-xl hover:shadow-glow-lg flex items-center justify-center group"
            >
              Start Generating <ArrowRight className="ml-2 w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </Link>
            <Link
              href="/dashboard/food-log"
              className="w-full sm:w-auto px-8 py-4 bg-white text-slate-700 border border-slate-200 rounded-full font-semibold text-lg hover:bg-slate-50 hover:border-slate-300 transition-all shadow-sm flex items-center justify-center"
            >
              Track Your Meals
            </Link>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-24 relative z-10">
        <div className="container mx-auto px-4 max-w-6xl">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4 tracking-tight">Everything You Need to Succeed</h2>
            <p className="text-slate-500 max-w-2xl mx-auto">Powerful tools designed to make healthy eating simple and automatic.</p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {[
              {
                icon: Utensils,
                title: "AI Meal Planning",
                desc: "Get customized 7-day meal plans based on your age, weight, and goals. Instantly generated by advanced AI.",
                color: "text-emerald-600",
                bg: "bg-emerald-50",
                href: "/dashboard/planner"
              },
              {
                icon: Activity,
                title: "Calorie Tracking",
                desc: "Easily log your daily meals and keep track of your calorie intake to stay on top of your diet targets.",
                color: "text-blue-600",
                bg: "bg-blue-50",
                href: "/dashboard/food-log"
              },
              {
                icon: User,
                title: "Personalized Profile",
                desc: "Update your stats and preferences anytime. Your plan adapts automatically as you progress towards your goals.",
                color: "text-purple-600",
                bg: "bg-purple-50",
                href: "/profile"
              }
            ].map((feature, i) => (
              <Link href={feature.href} key={i} className="bg-white rounded-3xl p-8 shadow-soft border border-slate-100/50 hover:-translate-y-2 hover:shadow-xl transition-all duration-300 flex flex-col items-start group cursor-pointer">
                <div className={`w-14 h-14 rounded-2xl flex items-center justify-center mb-6 transition-transform group-hover:scale-110 ${feature.bg}`}>
                  <feature.icon className={`w-6 h-6 ${feature.color}`} />
                </div>
                <h3 className="text-xl font-bold text-slate-900 mb-4">{feature.title}</h3>
                <p className="text-slate-500 leading-relaxed text-sm md:text-base">
                  {feature.desc}
                </p>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-24 bg-white border-y border-slate-100">
        <div className="container mx-auto px-4 max-w-6xl">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-x-8 gap-y-12 text-center divide-x-0 md:divide-x divide-slate-100">
            {[
              { label: "Meal Plans Generated", value: "10k+", icon: TrendingUp },
              { label: "Meals Logged", value: "50k+", icon: Activity },
              { label: "Goal Achievement", value: "95%", icon: ShieldCheck },
              { label: "User Rating", value: "4.9/5", icon: Sparkles },
            ].map((stat, i) => (
              <div key={i} className="flex flex-col items-center">
                <stat.icon className="w-6 h-6 text-emerald-500 mb-4 opacity-80" />
                <div className="text-4xl font-extrabold text-slate-900 mb-2 tracking-tight">{stat.value}</div>
                <div className="text-sm font-medium text-slate-500">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-32 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-slate-900 via-slate-800 to-emerald-900 z-0" />
        <div className="absolute inset-0 bg-[url('/grid.svg')] opacity-10 z-0" />

        <div className="container mx-auto px-4 relative z-10 text-center text-white max-w-4xl">
          <h2 className="text-4xl md:text-5xl font-extrabold mb-6 tracking-tight">Ready to Transform Your Diet?</h2>
          <p className="text-lg md:text-xl mb-10 text-slate-300 max-w-2xl mx-auto leading-relaxed">
            Join thousands of users who have taken control of their nutrition, health, and fitness with DietPro's premium tools.
          </p>
          <Link
            href="/signup"
            className="inline-flex px-10 py-5 bg-emerald-500 text-white rounded-full font-bold text-lg hover:bg-emerald-400 hover:scale-105 transition-all duration-300 shadow-glow-lg items-center justify-center"
          >
            Start Your Journey For Free
          </Link>
        </div>
      </section>

    </div>
  );
}
